### ISSUE TITLE
need dummy token for account under age 18

### ISSUE THREAD

**Issue by alliekatu** [kay-el-zed/HaloMCC-DiscordRPC#14]
it seems if an account is set under 18, requests can't be made with it's token. it stops here
![error](https://user-images.githubusercontent.com/29852001/120907585-c9b8e680-c630-11eb-8eac-619f04cc67d0.png) 
and won't progress forward. talked to gurrman and was told to make an issue here.

**Comment by Gurrman375** [comment]
Here is a test build for a fix. Used my little sisters account for testing.
https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.4(Dummy)
