### ISSUE TITLE
Local Host Not Connecting

### ISSUE THREAD

**Issue by Coolcakes** [kay-el-zed/HaloMCC-DiscordRPC#17]
I've Tried copying the link after I sign into Microsoft.

It brings me to local host which is not connecting.

I've disabled my firewall, Check my proxy settings in my browser and no luck.

Tried running Firefox and still didn't work

Running Windows 10

plz help,

**Comment by Gurrman375** [comment]
@Coolcakes send me the error.
also the website should look like:
![image](https://user-images.githubusercontent.com/25113575/193939101-ed3db13e-3a23-4fd0-ace4-79e8107267e1.png)
