### ISSUE TITLE
Just posts "activity" in command line repeatedly

### ISSUE THREAD

**Issue by Zareal** [kay-el-zed/HaloMCC-DiscordRPC#8]
Been trying to set this up but all I get after creating a token and starting RPC  (either normal or modified) is:

"Discord RPC not running. Starting!
Discord RPC Started
'activity'
'activity'
'activity'
'activity'
'activity'
'activity'

With "activity" repeating ad nauseum. Not sure what's going wrong, can post debug output if necessary.

**Comment by Gurrman375** [comment]
Currently working on a full rewrite of the code. Can you post what you are trying to run Halo on? (Xbox, Windows Store, or Steam)

**Comment by Zareal** [comment]
I'm running on Windows 10, the Windows store version via the Xbox Beta app/gamepass.

**Comment by itzaidan** [comment]
I have the same issue using the same thing.

**Comment by Gurrman375** [comment]
I leave this issue opened for now till I'm sure the new build fixes these issues.

**Comment by Gurrman375** [comment]
Check the fix here: https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.0

**Comment by itzaidan** [comment]
> Check the fix here: https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.0

Downloaded the latest release v0.3.1 (and tried 0.3.0 as well) but now I'm getting a different error `XRError: incorrect header check`

![image](https://user-images.githubusercontent.com/32919847/118734620-047eea00-b7fc-11eb-8ed6-545ace314595.png)

I also tried adding you on Discord but your name is invalid.

**Comment by Gurrman375** [comment]
My current discord is Gurr#8106. Usually the `XRError: incorrect header check` means you are entering the wrong email or password or xuid.

**Comment by itzaidan** [comment]
I'm pretty sure I've put in everything correctly, could it possibly be that I have 2FA on my account?

**Comment by Gurrman375** [comment]
I haven't set up oath yet so that could be a factor.

**Comment by Gurrman375** [comment]
Added Oauth 2.0. Should fix your issue now. https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.2

**Comment by Gurrman375** [comment]
With the latest release this should be fixed.
