### ISSUE TITLE
Not recognizing system change

### ISSUE THREAD

**Issue by LieutenantSugar** [kay-el-zed/HaloMCC-DiscordRPC#9]
This may be a bug on Xbox's part, but the presence does not seem to pick up on the fact that I have quit MCC on PC via Steam and launched it on Xbox, so it still displays that I am playing it on PC, even though I'm not. I tried reauthenticating a token, but that didn't fix it.

**Comment by Gurrman375** [comment]
Thanks for the feedback. The reason this happens is because the discord instance does not close for some reason. I'm working on rewriting the system to fix this and a couple issues. (If I had a few people to work with that would be helpful.)

**Comment by Gurrman375** [comment]
After one whole year I fixed it. Check around today for the new build.

**Comment by Gurrman375** [comment]
Finally fixed it check out: https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.2
